### ISSUE TITLE
Internal Delegation for toggling DebugHudState 

### ISSUE THREAD

**Issue by Ali-RS** [Simsilica/SiO2#2]
Wouldn't it be better for DebugHudState to decouple toggling for
`FunctionId HUD_TOGGLE = new FunctionId("Show Debug HUD");`
by delegating it internally (inside the DebugHudState class)
`inputMapper.addDelegate( HUD_TOGGLE, this, "toggleHud" );` ?

So we just need to map it to a key from our app like
`inputMapper.map(DebugHudState.HUD_TOGGLE , KeyInput.XXX);`

**Comment by pspeed42** [comment]
I go back and forth on that even in my own states.  Making it external means the user can avoid mapping it at all if they never intend to control it with keys.  This could be useful if you don't want to have to filter out a whole bunch of random FunctionIds in a key mapping GUI.  But yeah, most of my states do register their function ID as you suggest... for convenience.  It's just slightly less flexible.

**Comment by Ali-RS** [comment]
I see, thanks for explanation.

**Comment by pspeed42** [comment]
You aren't wrong to want this so I'm going to reopen the issue while I think about it.  As I said, I'm on the fence... and if the only bad side-effect is that people who want to have to filter it from their key mapping screens, well that might be acceptable.  After all, most people may still want to map their debug HUD toggle through this screen.

**Comment by pspeed42** [comment]
Ok, after thinking about this some more and letting is simmer... I kind of think leaving it external is best.  The reasoning is that I sometimes find myself 'ganging' state like this off of the same function.  For example, a debug key might toggle this state, a console state, and some other debugging features simultaneously.  Or certain debug functions may close other states.

The toggling on/off of a single state based on a function ID is a pretty specific use-case and maybe 180 degrees incompatible with other use-cases.

I'm still open to arguments to the contrary...and open to adapters/examples on easy ways to quick-set this externally.  For now I will close this issue, though.
