### ISSUE TITLE
NPE in CompositeAppState when adding child before initialization

### ISSUE THREAD

**Issue by NemesisMate** [Simsilica/SiO2#5]
If the **addChild** is called (on `CompositeAppState`) between the attach and initialization processes it throws a NPE due to:

```
        if( attached ) {
            getApplication().getStateManager().attach(state);
        }
```

the the application being null (it is being set on the `BaseAppState` initialization). So, this check should be if it is initialized instead of attached or the application should be set on the attachment moment instead of initialization in order to fix this issue.

**Comment by pspeed42** [comment]
This should be fixed now in the latest version.  Reopen if not.
