### ISSUE TITLE
Add java sourceCompatibility in build.gradle

### ISSUE THREAD

**Issue by Ali-RS** [Simsilica/SiO2#8]
Please add `sourceCompatibility = 1.7`  in `build.gradle` file so it can be compiled on java 9 onward.
Please consider this on your other libraries also (Lemur, Zay-ES, SimEthereal, SimMath)

**Comment by pspeed42** [comment]
See commit: https://github.com/Simsilica/SiO2/commit/b828b98f6c89e3f317208db8476ac01ef862a3dc

**Comment by Ali-RS** [comment]
Thanks :)
